version: 2.1

orbs:
  android: circleci/android@1.0.3
commands:
  checkout_secrets:
    steps:
      - run:
          name: Checkout Secrets
          command: |
            git clone git@github.com:bferris1/menus-app-secrets.git ~/secrets
            cp ~/secrets/google-services.json ./app/google-services.json
            cp ~/secrets/androidkey.jks ./app/androidkey.jks
            echo keyAlias=$keyAlias > keystore.properties
            echo keyPassword=$keyPassword >> keystore.properties
            echo storePassword=$storePassword >> keystore.properties


jobs:
  build:
    executor:
      name: android/android-machine
      resource-class: medium

    steps:
      - checkout
      - checkout_secrets
      - android/restore-gradle-cache:
          cache-prefix: v1
      - run:
          name: Run Tests
          command: ./gradlew test
      - run:
          name: Build Debug
          command: ./gradlew assembleDebug
      - run:
          name: Build Release
          command: ./gradlew assembleRelease bundleRelease
      - when:
          condition:
            equal: [circle_android_tests, << pipeline.git.branch >>]
          steps:
            - android/start-emulator-and-run-tests:
                system-image: system-images;android-29;default;x86
                restore-gradle-cache-post-emulator-launch: false
                save-gradle-cache: false
      - android/save-gradle-cache:
          cache-prefix: v1
      - store_artifacts:
          path: app/build/outputs/apk
          destination: apks
      - store_artifacts:
          path: app/build/outputs/bundle
          destination: bundle
      - store_test_results:
          path: app/build/test-results