version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:
  build:
    executor:
      name: android/android
      sdk-version: "29"

    steps:
      - checkout
      - run:
          name: Checkout Secrets
          command: |
            git clone git@github.com:bferris1/menus-app-secrets.git ~/secrets
            cp ~/secrets/google-services.json ./app/google-services.json
            cp ~/secrets/androidkey.jks ./app/androidkey.jks
            echo keyAlias=$keyAlias > keystore.properties
            echo keyPassword=$keyPassword >> keystore.properties
            echo storePassword=$storePassword >> keystore.properties
      - run:
          name: Assemble Debug
          command: ./gradlew clean check assembleDebug
      - run:
          name: Assemble Release
          command: ./gradlew assembleRelease bundleRelease
      - android/start-emulator-and-run-tests:
          system-image: system-images;android-29;default;x86
      - store_artifacts:
          path: app/build/outputs/apk
          destination: apks
      - store_artifacts:
          path: app/build/outputs/bundle
          destination: bundle
