version: 2.1

orbs:
 android: circleci/android@0.2.1

jobs:
  build:
    executor:
      name: android/android
      sdk-version: "29"

    steps:
      - checkout
      - run:
          name: Assemble
          command: ./gradlew clean assembleDebug

      - store_artifacts:
          path: app/build/outputs/apk
          destination: apks
